# Generated by Django 6.1 on 2026-08-13 14:29

import django.db.models.deletion
import structures.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('asset_type', models.CharField(choices=[('STR', 'Structure'), ('CUL', 'Culvert')], db_index=True, max_length=3)),
                ('type_details', models.CharField(blank=True, max_length=200)),
                ('batch', models.CharField(blank=True, max_length=10)),
                ('route_new', models.CharField(blank=True, max_length=50, verbose_name='New route name')),
                ('route_old', models.CharField(blank=True, max_length=50, verbose_name='Old route name')),
                ('google_maps_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['structure_code'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.CharField(db_index=True, default='Visit 2', max_length=30)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('complete', 'Complete')], db_index=True, default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='structures.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset__structure_code'],
            },
        ),
        migrations.CreateModel(
            name='CulvertData',
            fields=[
                ('carriageway_width_mm', models.FloatField(blank=True, null=True, verbose_name='Carriageway width (mm)')),
                ('carriageway_rhs_verge_width_mm', models.FloatField(blank=True, null=True, verbose_name='RHS verge width (mm)')),
                ('carriageway_lhs_verge_width_mm', models.FloatField(blank=True, null=True, verbose_name='LHS verge width (mm)')),
                ('carriageway_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('overall_condition', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=10, verbose_name='Overall condition')),
                ('overall_condition_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('general_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cul_data', serialize=False, to='structures.inspection')),
                ('headwall_rhs_length_mm', models.FloatField(blank=True, null=True, verbose_name='RHS headwall length (mm)')),
                ('headwall_rhs_width_mm', models.FloatField(blank=True, null=True, verbose_name='RHS headwall width (mm)')),
                ('headwall_rhs_height_mm', models.FloatField(blank=True, null=True, verbose_name='RHS headwall height (mm)')),
                ('headwall_lhs_length_mm', models.FloatField(blank=True, null=True, verbose_name='LHS headwall length (mm)')),
                ('headwall_lhs_width_mm', models.FloatField(blank=True, null=True, verbose_name='LHS headwall width (mm)')),
                ('headwall_lhs_height_mm', models.FloatField(blank=True, null=True, verbose_name='LHS headwall height (mm)')),
                ('headwall_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('box_span_mm', models.FloatField(blank=True, null=True, verbose_name='Span (mm)')),
                ('box_abutment_height_mm', models.FloatField(blank=True, null=True, verbose_name='Abutment height (mm)')),
                ('box_slab_depth_mm', models.FloatField(blank=True, null=True, verbose_name='Slab depth (mm)')),
                ('box_slab_width_mm', models.FloatField(blank=True, null=True, verbose_name='Slab width (mm)')),
                ('box_cover_depth_mm', models.FloatField(blank=True, null=True, verbose_name='Cover depth (mm)')),
                ('box_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('pipe_diameter_mm', models.FloatField(blank=True, null=True, verbose_name='Diameter (mm)')),
                ('pipe_thickness_mm', models.FloatField(blank=True, null=True, verbose_name='Pipe thickness (mm)')),
                ('pipe_cover_depth_mm', models.FloatField(blank=True, null=True, verbose_name='Cover depth (mm)')),
                ('pipe_notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Culvert data',
                'verbose_name_plural': 'Culvert data',
            },
        ),
        migrations.CreateModel(
            name='StructureData',
            fields=[
                ('carriageway_width_mm', models.FloatField(blank=True, null=True, verbose_name='Carriageway width (mm)')),
                ('carriageway_rhs_verge_width_mm', models.FloatField(blank=True, null=True, verbose_name='RHS verge width (mm)')),
                ('carriageway_lhs_verge_width_mm', models.FloatField(blank=True, null=True, verbose_name='LHS verge width (mm)')),
                ('carriageway_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('overall_condition', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=10, verbose_name='Overall condition')),
                ('overall_condition_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('general_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='str_data', serialize=False, to='structures.inspection')),
                ('parapet_rhs_length_mm', models.FloatField(blank=True, null=True, verbose_name='RHS parapet length (mm)')),
                ('parapet_rhs_width_mm', models.FloatField(blank=True, null=True, verbose_name='RHS parapet width (mm)')),
                ('parapet_rhs_height_mm', models.FloatField(blank=True, null=True, verbose_name='RHS parapet height (mm)')),
                ('parapet_lhs_length_mm', models.FloatField(blank=True, null=True, verbose_name='LHS parapet length (mm)')),
                ('parapet_lhs_width_mm', models.FloatField(blank=True, null=True, verbose_name='LHS parapet width (mm)')),
                ('parapet_lhs_height_mm', models.FloatField(blank=True, null=True, verbose_name='LHS parapet height (mm)')),
                ('parapet_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('soffit_span_mm', models.FloatField(blank=True, null=True, verbose_name='Span (mm)')),
                ('soffit_thickness_mm', models.FloatField(blank=True, null=True, verbose_name='Thickness (mm)')),
                ('soffit_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('abutment_height_mm', models.FloatField(blank=True, null=True, verbose_name='Height (mm)')),
                ('abutment_thickness_mm', models.FloatField(blank=True, null=True, verbose_name='Thickness (mm)')),
                ('abutment_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('headwall_height_mm', models.FloatField(blank=True, null=True, verbose_name='Height (mm)')),
                ('headwall_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('wingwall_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('concrete_reinforced', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Reinforced')),
                ('concrete_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('masonry_block_size_mm', models.FloatField(blank=True, null=True, verbose_name='Block size (mm)')),
                ('masonry_joint_thickness_mm', models.FloatField(blank=True, null=True, verbose_name='Joint thickness (mm)')),
                ('masonry_arch_barrel_block_size_mm', models.FloatField(blank=True, null=True, verbose_name='Arch barrel block size (mm)')),
                ('masonry_arch_barrel_joint_thickness_mm', models.FloatField(blank=True, null=True, verbose_name='Arch barrel joint thickness (mm)')),
                ('masonry_notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Structure data',
                'verbose_name_plural': 'Structure data',
            },
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('abutments_pier', 'Abutments / pier'), ('box', 'Box'), ('carriageway', 'Carriageway'), ('concrete', 'Concrete'), ('general_notes', 'General notes'), ('headwall', 'Headwall'), ('masonry', 'Masonry'), ('overall_condition', 'Overall condition'), ('parapet', 'Parapet'), ('pipe', 'Pipe'), ('soffit_arch', 'Soffit / arch'), ('wingwalls', 'Wingwalls')], db_index=True, max_length=40)),
                ('photo', models.ImageField(upload_to=structures.models.photo_upload_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='structures.inspection')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section_key', 'order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('abutments_pier', 'Abutments / pier'), ('box', 'Box'), ('carriageway', 'Carriageway'), ('concrete', 'Concrete'), ('general_notes', 'General notes'), ('headwall', 'Headwall'), ('masonry', 'Masonry'), ('overall_condition', 'Overall condition'), ('parapet', 'Parapet'), ('pipe', 'Pipe'), ('soffit_arch', 'Soffit / arch'), ('wingwalls', 'Wingwalls')], max_length=40)),
                ('is_complete', models.BooleanField(default=False)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_progress', to='structures.inspection')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Section progress',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('engineer', 'Field Engineer'), ('reviewer', 'Reviewer (Read Only)')], default='engineer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='inspection',
            constraint=models.UniqueConstraint(fields=('asset', 'visit'), name='unique_inspection_per_asset_visit'),
        ),
        migrations.AddConstraint(
            model_name='sectionprogress',
            constraint=models.UniqueConstraint(fields=('inspection', 'section_key'), name='unique_section_per_inspection'),
        ),
    ]
