# Generated by Django 6.1 on 2026-08-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
