# Generated by Django 6.1 on 2026-08-14 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0002_asset_latitude_asset_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionprogress',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='inspection',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
