# Generated by Django 6.1 on 2026-08-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0004_asset_created_at_asset_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionprogress',
            name='accuracy_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionprogress',
            name='fixed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionprogress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionprogress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
